stages:
- test

language: c

cache:
  npm: true

fast_finish: true

jobs:
  include:
  - stage: test
    env:
    - JOBNAME="Linux/x86-64 Node.js Correctness Tests"
    os: linux
    dist: bionic
    before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then script/apt-get-install-deps.sh; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then script/brew-install-deps.sh; fi
    install:
    - npm install
    script:
    - npm run lint
    - node test/*.test.js
  - stage: test
    env:
    - JOBNAME="Linux/x86-64 ShadowNode Correctness Tests"
    os: linux
    dist: bionic
    before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then script/apt-get-install-deps.sh; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then script/brew-install-deps.sh; fi
    - script/install-shadow-node.sh 0.11.6
    install:
    - npm install
    script:
    - npm run lint
    - iotjs test/*.test.js
